/*curl --request GET \
     --url 'https://api.themoviedb.org/3/movie/447144/credits?language=en-US' \
     --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0NjgyOWZhMWY2NzdmMjkwZmQ3NTAyNWFmOGI0N2UyMSIsIm5iZiI6MTcxOTY3MjIzNC4zMDIsInN1YiI6IjY2ODAxZGFhMjhkMzA2OTI2NzViZTZiNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.V6-Px6XK3mzZbcoyTrOmxgROWXW8xsyr0QzjUgkkxQk' \
     --header 'accept: application/json' */


export const credits = {
  "id": 447144,
  "cast": [
    {
      "adult": false,
      "gender": 2,
      "id": 7626,
      "known_for_department": "Production",
      "name": "Avi Arad",
      "original_name": "Avi Arad",
      "popularity": 1.2561,
      "profile_path": "/cxmqw0anGfxC7RwUNQj3EwhX9pP.jpg",
      "cast_id": 0,
      "character": "Himself",
      "credit_id": "58c97b4cc3a36875a600ac63",
      "order": 0
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1245564,
      "known_for_department": "Acting",
      "name": "John Cassaday",
      "original_name": "John Cassaday",
      "popularity": 0.0611,
      "profile_path": null,
      "cast_id": 1,
      "character": "Himself",
      "credit_id": "58c97b5fc3a36875f800bf1a",
      "order": 1
    },
    {
      "adult": false,
      "gender": 2,
      "id": 934847,
      "known_for_department": "Acting",
      "name": "Chris Claremont",
      "original_name": "Chris Claremont",
      "popularity": 0.3863,
      "profile_path": "/wp5aESx8Hqa0aq4sN2m3L34FH3N.jpg",
      "cast_id": 2,
      "character": "Himself",
      "credit_id": "58c97b67c3a368758300b989",
      "order": 2
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7624,
      "known_for_department": "Writing",
      "name": "Stan Lee",
      "original_name": "Stan Lee",
      "popularity": 2.4579,
      "profile_path": "/kKeyWoFtTqOPsbmwylNHmuB3En9.jpg",
      "cast_id": 3,
      "character": "Himself",
      "credit_id": "58c97b6e925141111300bdff",
      "order": 3
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1777042,
      "known_for_department": "Acting",
      "name": "David Cockrum",
      "original_name": "David Cockrum",
      "popularity": 0.0214,
      "profile_path": null,
      "cast_id": 4,
      "character": "Himself",
      "credit_id": "58c97b85c3a36875d500b4da",
      "order": 4
    },
    {
      "adult": false,
      "gender": 2,
      "id": 10850,
      "known_for_department": "Production",
      "name": "Kevin Feige",
      "original_name": "Kevin Feige",
      "popularity": 1.6436,
      "profile_path": "/2XZT80gR72to084pEj4f0SCDmDn.jpg",
      "cast_id": 5,
      "character": "Himself",
      "credit_id": "58c97b8e925141111300be0d",
      "order": 5
    },
    {
      "adult": false,
      "gender": 2,
      "id": 207202,
      "known_for_department": "Acting",
      "name": "Jim Lee",
      "original_name": "Jim Lee",
      "popularity": 0.6426,
      "profile_path": "/2L9XnGqDyEy5l49VCk3svKxyMIM.jpg",
      "cast_id": 6,
      "character": "Himself",
      "credit_id": "58c97b9592514108380022fc",
      "order": 6
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1488775,
      "known_for_department": "Acting",
      "name": "Adam Kubert",
      "original_name": "Adam Kubert",
      "popularity": 0.0589,
      "profile_path": null,
      "cast_id": 7,
      "character": "Himself",
      "credit_id": "58c97ba5c3a36875e800c08b",
      "order": 7
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1286900,
      "known_for_department": "Acting",
      "name": "Andy Kubert",
      "original_name": "Andy Kubert",
      "popularity": 0.2509,
      "profile_path": null,
      "cast_id": 8,
      "character": "Himself",
      "credit_id": "58c97bacc3a36875f800bf3e",
      "order": 8
    },
    {
      "adult": false,
      "gender": 2,
      "id": 89026,
      "known_for_department": "Writing",
      "name": "Scott Lobdell",
      "original_name": "Scott Lobdell",
      "popularity": 0.159,
      "profile_path": null,
      "cast_id": 9,
      "character": "Himself",
      "credit_id": "58c97bb5925141111300be20",
      "order": 9
    },
    {
      "adult": false,
      "gender": 2,
      "id": 87172,
      "known_for_department": "Writing",
      "name": "Mark Millar",
      "original_name": "Mark Millar",
      "popularity": 0.3516,
      "profile_path": "/oK9I2KfVM7zZZd6dD1gKBH8WrsX.jpg",
      "cast_id": 10,
      "character": "Himself",
      "credit_id": "58c97bbdc3a36836b40022c8",
      "order": 10
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1222480,
      "known_for_department": "Writing",
      "name": "Fabian Nicieza",
      "original_name": "Fabian Nicieza",
      "popularity": 0.3055,
      "profile_path": "/vV0VKVThe1o6fyS6SCRAlVNVdLX.jpg",
      "cast_id": 11,
      "character": "Himself",
      "credit_id": "58c97bc79251410838002317",
      "order": 11
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1356065,
      "known_for_department": "Acting",
      "name": "Louise Simonson",
      "original_name": "Louise Simonson",
      "popularity": 0.3294,
      "profile_path": "/kGT0XeZIC9oufqIGLF5lAe3wG6I.jpg",
      "cast_id": 12,
      "character": "Herself",
      "credit_id": "58c97bef925141111300be48",
      "order": 12
    },
    {
      "adult": false,
      "gender": 2,
      "id": 173658,
      "known_for_department": "Writing",
      "name": "Len Wein",
      "original_name": "Len Wein",
      "popularity": 0.4891,
      "profile_path": "/jA38DskVXNIryKgPgc9Tc3GyaGH.jpg",
      "cast_id": 13,
      "character": "Himself",
      "credit_id": "58c97bf6c3a36836b40022e1",
      "order": 13
    },
    {
      "adult": false,
      "gender": 2,
      "id": 2137087,
      "known_for_department": "Crew",
      "name": "Dave Cockrum",
      "original_name": "Dave Cockrum",
      "popularity": 0.0847,
      "profile_path": "/mrglhlJzipPgh71tM0QWiCdWAm9.jpg",
      "cast_id": 14,
      "character": "Himself",
      "credit_id": "5bae1b4e92514150f104eb08",
      "order": 14
    }
  ],
  "crew": []
}